# Generated by Django 2.0.3 on 2018-03-24 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20180324_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 22, 6, 36, 956455, tzinfo=utc), verbose_name='published date'),
        ),
    ]
