# Generated by Django 2.0.3 on 2018-03-24 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20180324_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 22, 7, 7, 261418, tzinfo=utc), verbose_name='published date'),
        ),
    ]
