# Generated by Django 2.0.3 on 2018-03-25 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20180324_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='img',
            field=models.ImageField(default='placeholder.png', upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 2, 58, 41, 188103, tzinfo=utc), verbose_name='published date'),
        ),
    ]
