# Generated by Django 2.0.3 on 2018-03-25 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20180325_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 3, 15, 59, 55871, tzinfo=utc), verbose_name='published date'),
        ),
    ]
