# Generated by Django 2.0.3 on 2018-03-25 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20180325_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 5, 35, 40, 889151, tzinfo=utc), verbose_name='published date'),
        ),
    ]
